name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '7'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '1'
      torch_is_nightly:
        description: PyTorch is nightly
        required: true
        type: string
        default: '0'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '8'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '1'
      extra_cuda_arch:
        description: Extra CUDA arch
        required: false
        type: string
        default: ''
      extra_wheel_version_suffix:
        description: Extra wheel version suffix
        required: false
        type: string
        default: ''
      is_python_abi3:
        description: Is Python ABI3
        required: false
        type: string
        default: ''

jobs:
  build-sageattn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: Jimver/cuda-toolkit@v0.2.22
        with:
          cuda: 12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false
          use-local-cache: false
          method: network
          sub-packages: '["nvcc", "cudart", "cublas", "cufft", "curand", "cusolver", "cusparse", "thrust", "nvrtc"]'

      - name: Build wheel
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          export CUDA_MINOR_VERSION="${{ inputs.cuda_minor }}"
          export TORCH_MINOR_VERSION="${{ inputs.torch_minor }}"
          export TORCH_PATCH_VERSION="${{ inputs.torch_patch }}"
          export TORCH_IS_NIGHTLY="${{ inputs.torch_is_nightly }}"
          python update_pyproject.py

          simpleindex simpleindex.toml &
          export PIP_INDEX_URL="http://127.0.0.1:8000"

          ARCH_LIST="8.0 8.6 8.9 9.0"
          if [[ "${{ inputs.cuda_minor }}" -gt "6" ]]; then
            ARCH_LIST="$ARCH_LIST 12.0"
          fi
          if [[ -n "${{ inputs.extra_cuda_arch }}" ]]; then
             ARCH_LIST="$ARCH_LIST ${{ inputs.extra_cuda_arch }}"
          fi
          export TORCH_CUDA_ARCH_LIST="$ARCH_LIST"

          export SAGEATTENTION_WHEEL_VERSION_SUFFIX="+cu12${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          export SAGEATTENTION_WHEEL_VERSION_SUFFIX="$SAGEATTENTION_WHEEL_VERSION_SUFFIX${{ inputs.extra_wheel_version_suffix }}"

          if [[ -n "${{ inputs.is_python_abi3 }}" ]]; then
            export CIBW_BUILD="{cp39-manylinux_x86_64,}"
          else
            if [[ "${{ inputs.torch_minor }}" -gt "5" ]]; then
              export CIBW_BUILD="{cp39-manylinux_x86_64,cp310-manylinux_x86_64,cp311-manylinux_x86_64,cp312-manylinux_x86_64,cp313-manylinux_x86_64}"
            else
              export CIBW_BUILD="{cp39-manylinux_x86_64,cp310-manylinux_x86_64,cp311-manylinux_x86_64,cp312-manylinux_x86_64}"
            fi
          fi
          export CIBW_BUILD_VERBOSITY="1"
          
          # Pass CUDA environment to cibuildwheel
          export CIBW_ENVIRONMENT="CUDA_HOME=/usr/local/cuda-12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }} LD_LIBRARY_PATH=/usr/local/cuda-12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}/lib64:$LD_LIBRARY_PATH PATH=/usr/local/cuda-12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}/bin:$PATH TORCH_CUDA_ARCH_LIST='$TORCH_CUDA_ARCH_LIST' SAGEATTENTION_WHEEL_VERSION_SUFFIX='$SAGEATTENTION_WHEEL_VERSION_SUFFIX'"
          
          # Configure cibuildwheel to use the correct Python
          export CIBW_BEFORE_BUILD="pip install -U pip setuptools wheel"
          export CIBW_REPAIR_WHEEL_COMMAND=""
          
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
