name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '7'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '1'
      torch_is_nightly:
        description: PyTorch is nightly
        required: true
        type: string
        default: '0'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '8'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '1'
      extra_cuda_arch:
        description: Extra CUDA arch
        required: false
        type: string
        default: ''
      extra_wheel_version_suffix:
        description: Extra wheel version suffix
        required: false
        type: string
        default: ''
      is_python_abi3:
        description: Is Python ABI3
        required: false
        type: string
        default: ''

jobs:
  build-sageattn:
    runs-on: ubuntu-latest
    steps:
      # Free up disk space
      - name: Free Disk Space
        run: |
          echo "Listing top 20 largest directories and files"
          sudo find / -type d -exec du -sh {} \; 2>/dev/null | sort -rh | head -n 20
          echo "Removing unnecessary large directories"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune -af
          df -h
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install CUDA toolkit using the Jimver/cuda-toolkit action
      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: 12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          method: network
          linux-local-args: ["--toolkit"]
          # Don't use sub-packages to avoid permission issues
          # sub-packages: '["nvcc", "cudart", "cublas", "cufft", "curand", "cusolver", "cusparse", "thrust", "nvrtc"]'
          
      - name: Verify CUDA installation
        run: |
          nvcc --version
          echo "CUDA_HOME=${{ steps.cuda-toolkit.outputs.CUDA_HOME }}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${{ steps.cuda-toolkit.outputs.LD_LIBRARY_PATH }}" >> $GITHUB_ENV
          echo "PATH=${{ steps.cuda-toolkit.outputs.PATH }}" >> $GITHUB_PATH

      - name: Build wheel
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          export CUDA_MINOR_VERSION="${{ inputs.cuda_minor }}"
          # Use PyTorch 2.6.0 which is available in PyPI
          export TORCH_MINOR_VERSION="6"
          export TORCH_PATCH_VERSION="0"
          export TORCH_IS_NIGHTLY="${{ inputs.torch_is_nightly }}"
          python update_pyproject.py

          simpleindex simpleindex.toml &
          export PIP_INDEX_URL="http://127.0.0.1:8000"

          ARCH_LIST="8.0 8.6 8.9 9.0"
          if [[ "${{ inputs.cuda_minor }}" -gt "6" ]]; then
            ARCH_LIST="$ARCH_LIST 12.0"
          fi
          if [[ -n "${{ inputs.extra_cuda_arch }}" ]]; then
             ARCH_LIST="$ARCH_LIST ${{ inputs.extra_cuda_arch }}"
          fi
          export TORCH_CUDA_ARCH_LIST="$ARCH_LIST"

          export SAGEATTENTION_WHEEL_VERSION_SUFFIX="+cu12${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          export SAGEATTENTION_WHEEL_VERSION_SUFFIX="$SAGEATTENTION_WHEEL_VERSION_SUFFIX${{ inputs.extra_wheel_version_suffix }}"

          if [[ -n "${{ inputs.is_python_abi3 }}" ]]; then
            export CIBW_BUILD="{cp39-manylinux_x86_64,}"
          else
            if [[ "${{ inputs.torch_minor }}" -gt "5" ]]; then
              export CIBW_BUILD="{cp39-manylinux_x86_64,cp310-manylinux_x86_64,cp311-manylinux_x86_64,cp312-manylinux_x86_64,cp313-manylinux_x86_64}"
            else
              export CIBW_BUILD="{cp39-manylinux_x86_64,cp310-manylinux_x86_64,cp311-manylinux_x86_64,cp312-manylinux_x86_64}"
            fi
          fi
          export CIBW_BUILD_VERBOSITY="1"
          
          # Pass CUDA environment to cibuildwheel
          export CIBW_ENVIRONMENT="CUDA_HOME=$CUDA_HOME LD_LIBRARY_PATH=$LD_LIBRARY_PATH TORCH_CUDA_ARCH_LIST='$TORCH_CUDA_ARCH_LIST' SAGEATTENTION_WHEEL_VERSION_SUFFIX='$SAGEATTENTION_WHEEL_VERSION_SUFFIX'"
          
          # Configure cibuildwheel to use the correct Python and install PyTorch
          # Use --no-cache-dir to avoid disk space issues
          export CIBW_BEFORE_BUILD="pip install --no-cache-dir -U pip setuptools wheel numpy torch==2.6.0"
          export CIBW_REPAIR_WHEEL_COMMAND=""
          
          # Skip the test phase to avoid Python detection issues
          export CIBW_TEST_SKIP="*"
          
          # Use manylinux2014 for better compatibility
          export CIBW_MANYLINUX_X86_64_IMAGE="manylinux2014"
          export CIBW_MANYLINUX_PYPY_X86_64_IMAGE="manylinux2014"
          
          # Limit Python versions to save disk space
          export CIBW_BUILD="cp39-manylinux_x86_64"
          
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
